CREATE TABLE FRANQUICIA (
    FRANQUICIA_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    CIUDAD VARCHAR(100)
);

CREATE TABLE SUCURSAL (
    ID_SUCURSAL BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_SUCURSAL VARCHAR(100),
    CIUDAD_SUCURSAL VARCHAR(100),
    FRANQUICIA_ID BIGINT,
    CONSTRAINT FK_SUCURSAL_FRANQUICIA
        FOREIGN KEY (FRANQUICIA_ID)
        REFERENCES FRANQUICIA(FRANQUICIA_ID)
);

CREATE TABLE PRODUCTO (
    ID_PRODUCTO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE_PRODUCTO VARCHAR(100),
    PRECIO DECIMAL(10,2),
    CANTIDAD_PRODUCTO INT,
    SUCURSAL_ID BIGINT,
    CONSTRAINT FK_PRODUCTO_SUCURSAL
        FOREIGN KEY (SUCURSAL_ID)
        REFERENCES SUCURSAL(ID_SUCURSAL)
);
